# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='usuario',
            name='agendas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usarios', to='agenda.Agenda'),
        ),
    ]
